# Generated by Django 5.2.4 on 2025-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador1', models.CharField(max_length=100)),
                ('jogador2', models.CharField(max_length=100)),
                ('vencedor', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
